items:

  - type: plain
    itemId: minecraft:map
    slotId: 53
    displayName: Š‹àF

  - type: amount
    itemId: minecraft:lime_stained_glass_pane
    slotId: 23
    displayName: +1
    sign: plus
    amount: 1

  - type: amount
    itemId: minecraft:lime_stained_glass_pane
    slotId: 24
    displayName: +10
    sign: plus
    amount: 10

  - type: amount
    itemId: minecraft:red_stained_glass_pane
    slotId: 21
    displayName: -1
    sign: minus
    amount: 1

  - type: amount
    itemId: minecraft:red_stained_glass_pane
    slotId: 20
    displayName: -10
    sign: minus
    amount: 10

  - type: buy
    itemId: minecraft:gold_ingot
    slotId: 41
    displayName: w“ü‚·‚é

  - type: transition
    itemId: minecraft:red_bed
    slotId: 39
    displayName: –ß‚é
    next: buy_page1
