items:

  - type: plain
    itemId: minecraft:map
    slotId: 53
    displayName: Š‹àF

  - type: transition
    itemId: minecraft:diamond_sword
    slotId: 24
    displayName: w“ü
    next: buy_page1

  - type: transition
    itemId: minecraft:emerald
    slotId: 20
    displayName: ”„‹p
    next: sell
